#use_frameworks!

platform :ios, '9.0'

target 'PodIJKMedia_Example' do
  pod 'PodIJKMedia', :podspec => '../PodIJKMedia.podspec'

  target 'PodIJKMedia_Tests' do
    inherit! :search_paths

    
  end
end
